# Generated by Django 5.2.7 on 2025-11-15 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
