# Generated by Django 5.2.7 on 2025-11-15 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_publicacion_latitude_publicacion_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
